### ISSUE TITLE
TypeError: this.debug is not a function

### ISSUE THREAD

**Issue by aminya** [idleberg/generator-atom-package-typescript#5]
```ps1
PS C:\Users\yahyaaba\Documents\GitHub\typescript> yo atom-package-typescript
TypeError: this.debug is not a function
    at C:\Users\yahyaaba\AppData\Roaming\npm\node_modules\generator-atom-package-typescript\node_modules\yeoman-generator\lib\index.js:695:12
    at new Promise (<anonymous>)
    at module.exports.run (C:\Users\yahyaaba\AppData\Roaming\npm\node_modules\generator-atom-package-typescript\node_modules\yeoman-generator\lib\index.js:692:21)
    at Environment.runGenerator (C:\Users\yahyaaba\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:616:22)
    at Environment.run (C:\Users\yahyaaba\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:603:17)
    at C:\Users\yahyaaba\AppData\Roaming\npm\node_modules\yo\lib\cli.js:167:11
    at Environment.resolver.lookup (C:\Users\yahyaaba\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:73:12)
    at init (C:\Users\yahyaaba\AppData\Roaming\npm\node_modules\yo\lib\cli.js:128:7)
    at pre (C:\Users\yahyaaba\AppData\Roaming\npm\node_modules\yo\lib\cli.js:87:3)
    at Object.<anonymous> (C:\Users\yahyaaba\AppData\Roaming\npm\node_modules\yo\lib\cli.js:216:3)
PS C:\Users\yahyaaba\Documents\GitHub\typescript>

```

**Comment by idleberg** [comment]
This appears to be caused by a bug in [`yeoman-generator`](https://www.npmjs.com/package/yeoman-generator):

```
TypeError: this.debug is not a function
    at C:\Users\yahyaaba\AppData\Roaming\npm\node_modules\generator-atom-package-typescript\node_modules\yeoman-generator\lib\index.js:695:12
```

**Comment by aminya** [comment]
Thank you this seems to be fixed
